apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-maven-run-
spec:
  pipelineRef:
    name: clone-maven
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-credentials
    secret:
      secretName: git-credentials
  params:
  - name: repo-url
    value: git@git.smartsteps.com:delivery/developer/ops/k8s_ops/demo.git
  - name: git-init
    value: hub.smartsteps.com/gitops/tektoncd/pipeline/cmd/git-init:v0.43.2
