apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-readme
  description: Read and display README file
spec:
  workspaces:
    - name: source
  steps:
  - name: read
    image: hub.smartsteps.com/public/toolbox:0.2.2
    script: |
      #!/usr/bin/env sh
      cat $(workspaces.source.path)/README.md
